// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"exam-system/classes/internal/types"
	"fmt"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
)

var (
	classFieldNames          = builder.RawFieldNames(&Class{})
	classRows                = strings.Join(classFieldNames, ",")
	classRowsExpectAutoSet   = strings.Join(stringx.Remove(classFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	classRowsWithPlaceHolder = strings.Join(stringx.Remove(classFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	classModel interface {
		Insert(ctx context.Context, data *Class) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Class, error)
		FindOneByClassCode(ctx context.Context, classCode string) (*Class, error)
		Update(ctx context.Context, data *Class) error
		Delete(ctx context.Context, id int64, teacherId int64) error
		FindByClassCode(ctx context.Context, classCode string) (*Class, error)
		FindAllByTeacherId(ctx context.Context, teacherId int64) ([]*types.ClassInfo, error)
		FindClassDetailByClassID(ctx context.Context, classID int64) (*types.ClassDetailResponse, error)
		FindClassesByUserId(ctx context.Context, userId int64) ([]*types.ClassInfo, error)
	}

	defaultClassModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Class struct {
		Id         int64  `db:"id"`          // 班级ID（主键）
		Name       string `db:"name"`        // 班级名称（即课程名称）
		TeacherId  int64  `db:"teacher_id"`  // 教师ID
		ClassCode  string `db:"class_code"`  // 班级唯一邀请码
		IsJoinable int64  `db:"is_joinable"` // 是否允许加入（0-禁止，1-允许）
	}
)

func newClassModel(conn sqlx.SqlConn) *defaultClassModel {
	return &defaultClassModel{
		conn:  conn,
		table: "`class`",
	}
}

func (m *defaultClassModel) Delete(ctx context.Context, id int64, teacherId int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ? and `teacher_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id, teacherId)
	return err
}

func (m *defaultClassModel) FindOne(ctx context.Context, id int64) (*Class, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", classRows, m.table)
	var resp Class
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClassModel) FindOneByClassCode(ctx context.Context, classCode string) (*Class, error) {
	var resp Class
	query := fmt.Sprintf("select %s from %s where `class_code` = ? limit 1", classRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, classCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClassModel) Insert(ctx context.Context, data *Class) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, classRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.TeacherId, data.ClassCode, data.IsJoinable)
	return ret, err
}

func (m *defaultClassModel) Update(ctx context.Context, newData *Class) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, classRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.TeacherId, newData.ClassCode, newData.IsJoinable, newData.Id)
	return err
}

func (m *defaultClassModel) tableName() string {
	return m.table
}

// FindByClassCode 根据class_code查找班级信息
func (m *defaultClassModel) FindByClassCode(ctx context.Context, classCode string) (*Class, error) {
	query := fmt.Sprintf("SELECT id, name, teacher_id, class_code, is_joinable FROM %s WHERE class_code = ? LIMIT 1", m.table)
	var class Class
	err := m.conn.QueryRowCtx(ctx, &class, query, classCode)
	if err != nil {
		return nil, err
	}
	return &class, nil
}

func (m *defaultClassModel) FindAllByTeacherId(ctx context.Context, teacherId int64) ([]*types.ClassInfo, error) {
	// 查询指定教师ID的所有班级，并获取教师名称
	query := `
        SELECT c.id, c.name AS class_name, c.class_code, c.is_joinable, u.name AS teacher_name
        FROM class c
        JOIN users u ON c.teacher_id = u.id
        WHERE c.teacher_id = ? `

	var classes []*types.ClassInfo

	// 执行查询
	err := m.conn.QueryRowsCtx(ctx, &classes, query, teacherId)
	if err != nil {
		return nil, err
	}

	return classes, nil
}
func (m *defaultClassModel) FindClassesByUserId(ctx context.Context, userId int64) ([]*types.ClassInfo, error) {
	query := `
        SELECT c.id, c.name AS class_name, c.class_code, c.is_joinable, u.name AS teacher_name
        FROM class_member cm
        JOIN class c ON cm.class_id = c.id
        JOIN users u ON c.teacher_id = u.id
        WHERE cm.user_id = ?
    `

	var classes []*types.ClassInfo

	err := m.conn.QueryRowsCtx(ctx, &classes, query, userId)
	if err != nil {
		return nil, err
	}

	return classes, nil
}

func (m *defaultClassModel) FindClassDetailByClassID(ctx context.Context, classID int64) (*types.ClassDetailResponse, error) {
	// 获取班级信息，包括班级创建人（教师）的姓名
	classQuery := `
        SELECT 
            c.id,               -- 获取班级ID
            c.name AS class_name,
            c.class_code,
            c.is_joinable,
            u.name AS teacher_name
        FROM 
            class c
        JOIN 
            users u ON c.teacher_id = u.id
        WHERE 
            c.id = ?
    `
	var classInfo types.ClassInfo
	err := m.conn.QueryRowCtx(ctx, &classInfo, classQuery, classID)
	if err != nil {
		return nil, err
	}

	// 获取班级成员信息
	membersQuery := `
        SELECT 
            cm.id AS class_member_id, 
            u.username, 
            u.name, 
            u.type AS user_type
        FROM 
            class_member cm
        JOIN 
            users u ON cm.user_id = u.id
        WHERE 
            cm.class_id = ?
    `
	var members []*types.ClassMemberDetail
	err = m.conn.QueryRowsCtx(ctx, &members, membersQuery, classID)
	if err != nil {
		return nil, err
	}

	// 构建返回结果
	return &types.ClassDetailResponse{
		ClassInfo:    classInfo, // 班级信息，包括ID
		ClassMembers: members,   // 班级成员
	}, nil
}
