// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"
	"time"

	"exam-system/users/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: createHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: deleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updatePwd",
				Handler: updatePwdhandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/loginOut",
				Handler: loginOutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: updateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/userList",
				Handler: userListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: detailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/createByFile",
				Handler: CreateByFileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
		rest.WithTimeout(3000*time.Millisecond),
	)
	server.AddRoutes(
		[]rest.Route{{Method: http.MethodPost,
			Path:    "/login",
			Handler: loginHandler(serverCtx)},
		}, rest.WithPrefix("/user"),
		rest.WithTimeout(3000*time.Millisecond))
}
