// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

// CreateClassRequest 用于表示创建班级的请求
type CreateClassRequest struct {
	ClassName  string `json:"className"`  // 班级名称
	IsJoinable int    `json:"isJoinable"` // 是否允许加入，0或1
}

// CreateClassResponse 用于返回创建班级的响应
type CreateClassResponse struct {
	Message   string `json:"message"`   // 响应消息
	ClassCode string `json:"classCode"` // 创建后的班级邀请码
}

// JoinClassRequest 用于表示加入班级的请求
type JoinClassRequest struct {
	ClassCode string `json:"classCode"` // 班级邀请码
}

// JoinClassResponse 用于表示加入班级的响应
type JoinClassResponse struct {
	Message string `json:"message"` // 响应消息
}

// ClassInfo 用于表示班级信息
type ClassInfo struct {
	ID          int64  `json:"classId,omitempty" db:"id"`               // 班级ID
	ClassName   string `json:"className,omitempty" db:"class_name"`     // 班级名称
	ClassCode   string `json:"classCode,omitempty" db:"class_code"`     // 班级邀请码
	IsJoinable  int    `json:"isJoinable,omitempty" db:"is_joinable"`   // 是否允许加入，0或1
	TeacherName string `json:"teacherName,omitempty" db:"teacher_name"` // 班级创建人
}

// ClassMemberDetail 用于表示班级成员的信息
type ClassMemberDetail struct {
	ClassMemberID int64  `json:"classMemberId" db:"class_member_id"` // 成员ID
	Username      string `json:"username" db:"username"`             // 成员用户名
	Name          string `json:"name" db:"name"`                     // 成员姓名
	UserType      int    `json:"userType" db:"user_type"`            // 成员类型，1为学生，2为教师等
}

// ClassListResponse 用于返回班级列表的响应
type ClassListResponse struct {
	ClassList []ClassInfo `json:"classList"` // 班级信息列表
}

// ClassDetailRequest 用于获取班级详情的请求
type ClassDetailRequest struct {
	ClassId int64 `json:"classId"` // 班级ID
}

// ClassDetailResponse 用于返回班级详情的响应
type ClassDetailResponse struct {
	ClassInfo    `json:"classInfo"`   // 班级信息
	ClassMembers []*ClassMemberDetail `json:"classMembers"` // 班级成员列表
}

// UpdateClassRequest 用于更新班级信息的请求
type UpdateClassRequest struct {
	ClassID     int64  `json:"classId"`     // 班级ID，必填
	ClassName   string `json:"className"`   // 班级名称，必填
	IsJoinable  int    `json:"isJoinable"`  // 是否允许加入，0或1
	RefreshCode bool   `json:"refreshCode"` // 是否刷新邀请码
}

// UpdateClassResponse 用于返回更新班级信息的响应
type UpdateClassResponse struct {
	Message   string `json:"message"`   // 响应消息
	ClassCode string `json:"classCode"` // 更新后的班级邀请码
}

// DeleteClassRequest 用于删除班级的请求
type DeleteClassRequest struct {
	ClassId int64 `json:"classId"` // 班级ID
}

// DeleteClassResponse 用于删除班级的响应
type DeleteClassResponse struct {
	Message string `json:"message"` //响应信息
}

// DeleteClassMemberRequest 用于删除成员的请求
type DeleteClassMemberRequest struct {
	MemberId int64 `json:"memberId"`
}

// DeleteClassMemberResponse 用于删除成员的响应
type DeleteClassMemberResponse struct {
	Message string `json:"message"`
}
